### ISSUE TITLE
Hi,Can you help me look this mistake?

### ISSUE THREAD

**Issue by Suelence-hu** [zjysteven/DVERGE#2]
![image](https://user-images.githubusercontent.com/39931365/109653258-c3cbe900-7b9b-11eb-934e-d0a324a9e6b8.png)

**Comment by zjysteven** [comment]
https://github.com/zjysteven/DVERGE/blob/9ab02549cf6073f57b8e2d1ae74c40ac0387fa28/train/train_dverge.py#L204

`writer` should be a SummaryWriter object, whereas in your case it somehow becomes a string.

**Comment by Suelence-hu** [comment]
> https://github.com/zjysteven/DVERGE/blob/9ab02549cf6073f57b8e2d1ae74c40ac0387fa28/train/train_dverge.py#L204
> 
> `writer` should be a SummaryWriter object, whereas in your case it somehow becomes a string.

https://github.com/zjysteven/DVERGE/issues/2
I have corrected it,but i come aross this mistake.

**Comment by Suelence-hu** [comment]
> o
![image](https://user-images.githubusercontent.com/39931365/109804821-a65f5380-7c5d-11eb-8753-9613ce336e2c.png)
I have corrected it ,but i come across this mistake.

**Comment by zjysteven** [comment]
@Suelence-hu [This](https://stackoverflow.com/questions/60146023/attributeerror-module-tensorflow-has-no-attribute-io) should be helpful.

Also, to avoid any other running time errors, I would suggest installing a new conda environment as instructed in the Readme.

**Comment by zjysteven** [comment]
@Suelence-hu I'm closing the issue now, but feel free to ask any other questions.
