### ISSUE TITLE
on calculate the robustness value(AdvT Rob)

### ISSUE THREAD

**Issue by yyf17** [zjysteven/DVERGE#4]
Thank you for your wonderful research. Please tell me how to calculate the robustness value of adversarial training (as shown in the figure below, AdvT Rob)? Since I didn't read the code carefully, I didn't find it in the relevant code.Thanks.
![image](https://user-images.githubusercontent.com/34536352/117597489-4367cc80-b178-11eb-8ded-d4b7e83ad7af.png)

**Comment by zjysteven** [comment]
The picture here showed the robusntess against transfer PGD attacks. We provide the attacked samples [here](https://drive.google.com/drive/folders/1i96Bk_bCWXhb7afSNp1t3woNjO1kAMDH) (see the instruction in "Data and pre-trained models" in the ReadMe). You just need to perform standard inference using the provided adversarial examples and the corresponding accuracy would give you the robustness in this table.

**Comment by zjysteven** [comment]
Closing this issue now, but feel free to ask if you have any further questions.
