### ISSUE TITLE
Code for decision region plots

### ISSUE THREAD

**Issue by ymerkli** [zjysteven/DVERGE#5]
Hi @zjysteven, thanks for this insightful work!

I was wondering if you could provide the code that produces the decision region plots that are shown in the paper (Figure 1, 7)? Some of the details of these plots are unclear to me:

1. From the paper, I understand that the vertical axis is along the adversarial direction and the horizontal axis along the direction of a random Rademacher vector. What do the values of these axis represent exactly?
2. How are the adversarial direction and the random Rademacher vector combined to obtain the final sample for which the model then produces the label being plotted in the decision region plot?

I think uploading the plotting code would help to better understand these plots :slightly_smiling_face:

**Comment by zjysteven** [comment]
Hi @ymerkli,

Thanks for your interest in our work and sorry about my late response.

We visualize the decision boundary based on the code [here](https://adversarial-ml-tutorial.org/adversarial_training/). Specifically, you can directly see a working example written in PyTorch in the section named "What is happening with these robust models?". The specific code we used for plotting is [here](https://drive.google.com/file/d/1KNoQGTXm3g_RBwE0a6IkrlSks4Wez_tN/view). The code is pretty messy, but the essential part starts from line 177. Hope it will help!

To answer your question, the values basically represent the distance that you perturb along a certain direction/axis. For example, the point (0.05, -0.03) corresponds to an perturbed image `x'`, and `x'=x+0.05*dir1-0.03*dir2`, where `x` is the clean image (represented by the origin of the plot), and `dir1`, `dir2` are the corresponding adversarial/rademacher vectors (of the same size as the image). Hope this concrete example will be helpful as well.

**Comment by zjysteven** [comment]
Added some description regarding the plot in the ReadMe and mentioned the values we used for the arguments in the code.

**Comment by zjysteven** [comment]
Closing this issue now, but feel free to ask if you have further questions.
